version: '3.8'

services:
  ydb:
    build: ./docker/ydb
    container_name: ydb_server
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
    environment:
      # YDB_ENDPOINT: "ydb:2136"
      YDB_DATABASE: "/local"
    hostname: localhost
    platform: linux/amd64


  postgres:
    build: ./docker/postgres
    container_name: postgres_server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres